export const roadmapData = [
  { id: 1, title: "APIs", slug: "apis", category: "Communication", difficulty: "Beginner" as const },
  { id: 2, title: "Webhooks", slug: "webhooks", category: "Communication", difficulty: "Beginner" as const },
  { id: 3, title: "REST vs GraphQL", slug: "rest-vs-graphql", category: "Communication", difficulty: "Intermediate" as const },
  { id: 4, title: "API Gateway", slug: "api-gateway", category: "Infrastructure", difficulty: "Intermediate" as const },
  { id: 5, title: "Load Balancers", slug: "load-balancers", category: "Infrastructure", difficulty: "Intermediate" as const },
  { id: 6, title: "Load Balancing Algorithms", slug: "load-balancing-algorithms", category: "Infrastructure", difficulty: "Advanced" as const },
  { id: 7, title: "Proxy vs Reverse Proxy", slug: "proxy-vs-reverse-proxy", category: "Infrastructure", difficulty: "Intermediate" as const },
  { id: 8, title: "Scalability", slug: "scalability", category: "Architecture", difficulty: "Intermediate" as const },
  { id: 9, title: "Availability", slug: "availability", category: "Architecture", difficulty: "Intermediate" as const },
  { id: 10, title: "SPOF (Single Point of Failure)", slug: "spof", category: "Architecture", difficulty: "Intermediate" as const },
  { id: 11, title: "CAP Theorem", slug: "cap-theorem", category: "Theory", difficulty: "Advanced" as const },
  { id: 12, title: "Database Types", slug: "database-types", category: "Database", difficulty: "Beginner" as const },
  { id: 13, title: "SQL vs NoSQL", slug: "sql-vs-nosql", category: "Database", difficulty: "Intermediate" as const },
  { id: 14, title: "ACID Transactions", slug: "acid-transactions", category: "Database", difficulty: "Intermediate" as const },
  { id: 15, title: "Database Indexes", slug: "database-indexes", category: "Database", difficulty: "Intermediate" as const },
  { id: 16, title: "Sharding vs Partitioning", slug: "sharding-vs-partitioning", category: "Database", difficulty: "Advanced" as const },
  { id: 17, title: "Consistent Hashing", slug: "consistent-hashing", category: "Database", difficulty: "Advanced" as const },
  { id: 18, title: "CDC (Change Data Capture)", slug: "cdc", category: "Database", difficulty: "Advanced" as const },
  { id: 19, title: "Caching", slug: "caching", category: "Performance", difficulty: "Beginner" as const },
  { id: 20, title: "Caching Strategies", slug: "caching-strategies", category: "Performance", difficulty: "Intermediate" as const },
  { id: 21, title: "Cache Eviction Policies", slug: "cache-eviction", category: "Performance", difficulty: "Intermediate" as const },
  { id: 22, title: "CDN (Content Delivery Network)", slug: "cdn", category: "Performance", difficulty: "Intermediate" as const },
  { id: 23, title: "Rate Limiting Algorithms", slug: "rate-limiting", category: "Security", difficulty: "Intermediate" as const },
  { id: 24, title: "Message Queues", slug: "message-queues", category: "Communication", difficulty: "Intermediate" as const },
  { id: 25, title: "Bloom Filters", slug: "bloom-filters", category: "Data Structures", difficulty: "Advanced" as const },
  { id: 26, title: "Idempotency", slug: "idempotency", category: "Theory", difficulty: "Intermediate" as const },
  { id: 27, title: "Concurrency vs Parallelism", slug: "concurrency-vs-parallelism", category: "Theory", difficulty: "Intermediate" as const },
  { id: 28, title: "Stateful vs Stateless Architecture", slug: "stateful-vs-stateless", category: "Architecture", difficulty: "Intermediate" as const },
  { id: 29, title: "Long Polling vs WebSockets", slug: "long-polling-vs-websockets", category: "Communication", difficulty: "Intermediate" as const },
  { id: 30, title: "Batch vs Stream Processing", slug: "batch-vs-stream", category: "Processing", difficulty: "Advanced" as const },
]
