export const roadmapData = [
  {
    id: 1,
    title: "APIs",
    url: "https://lnkd.in/dsbwPZ6N",
    category: "Communication",
    difficulty: "Beginner" as const,
  },
  {
    id: 2,
    title: "Webhooks",
    url: "https://lnkd.in/geHxGX-7",
    category: "Communication",
    difficulty: "Beginner" as const,
  },
  {
    id: 3,
    title: "REST vs GraphQL",
    url: "https://lnkd.in/gM5VHKQS",
    category: "Communication",
    difficulty: "Intermediate" as const,
  },
  {
    id: 4,
    title: "API Gateway",
    url: "https://lnkd.in/gtyXmvf4",
    category: "Infrastructure",
    difficulty: "Intermediate" as const,
  },
  {
    id: 5,
    title: "Load Balancers",
    url: "https://lnkd.in/dzM7VDKq",
    category: "Infrastructure",
    difficulty: "Intermediate" as const,
  },
  {
    id: 6,
    title: "Load Balancing Algorithms",
    url: "https://lnkd.in/gvxfwEUr",
    category: "Infrastructure",
    difficulty: "Advanced" as const,
  },
  {
    id: 7,
    title: "Proxy vs Reverse Proxy",
    url: "https://lnkd.in/gMTtidBq",
    category: "Infrastructure",
    difficulty: "Intermediate" as const,
  },
  {
    id: 8,
    title: "Scalability",
    url: "https://lnkd.in/gPGhW-qK",
    category: "Architecture",
    difficulty: "Intermediate" as const,
  },
  {
    id: 9,
    title: "Availability",
    url: "https://lnkd.in/gQk2p4_6",
    category: "Architecture",
    difficulty: "Intermediate" as const,
  },
  {
    id: 10,
    title: "SPOF (Single Point of Failure)",
    url: "https://lnkd.in/gw_uHZWn",
    category: "Architecture",
    difficulty: "Intermediate" as const,
  },
  {
    id: 11,
    title: "CAP Theorem",
    url: "https://lnkd.in/g_tFqJJb",
    category: "Theory",
    difficulty: "Advanced" as const,
  },
  {
    id: 12,
    title: "Database Types",
    url: "https://lnkd.in/gDxtZVE2",
    category: "Database",
    difficulty: "Beginner" as const,
  },
  {
    id: 13,
    title: "SQL vs NoSQL",
    url: "https://lnkd.in/gHyC9qWc",
    category: "Database",
    difficulty: "Intermediate" as const,
  },
  {
    id: 14,
    title: "ACID Transactions",
    url: "https://lnkd.in/dB3QHiMz",
    category: "Database",
    difficulty: "Intermediate" as const,
  },
  {
    id: 15,
    title: "Database Indexes",
    url: "https://lnkd.in/g_-bQWtA",
    category: "Database",
    difficulty: "Intermediate" as const,
  },
  {
    id: 16,
    title: "Sharding vs Partitioning",
    url: "https://lnkd.in/dk2276Ve",
    category: "Database",
    difficulty: "Advanced" as const,
  },
  {
    id: 17,
    title: "Consistent Hashing",
    url: "https://lnkd.in/gR9wFDpz",
    category: "Database",
    difficulty: "Advanced" as const,
  },
  {
    id: 18,
    title: "CDC (Change Data Capture)",
    url: "https://lnkd.in/gWhGwh9Z",
    category: "Database",
    difficulty: "Advanced" as const,
  },
  {
    id: 19,
    title: "Caching",
    url: "https://lnkd.in/gBSeTstS",
    category: "Performance",
    difficulty: "Beginner" as const,
  },
  {
    id: 20,
    title: "Caching Strategies",
    url: "https://lnkd.in/dVk7nZ_Y",
    category: "Performance",
    difficulty: "Intermediate" as const,
  },
  {
    id: 21,
    title: "Cache Eviction Policies",
    url: "https://lnkd.in/gQAEXEmq",
    category: "Performance",
    difficulty: "Intermediate" as const,
  },
  {
    id: 22,
    title: "CDN (Content Delivery Network)",
    url: "https://lnkd.in/gaW4Vkpy",
    category: "Performance",
    difficulty: "Intermediate" as const,
  },
  {
    id: 23,
    title: "Rate Limiting Algorithms",
    url: "https://lnkd.in/gYDxg8XY",
    category: "Security",
    difficulty: "Intermediate" as const,
  },
  {
    id: 24,
    title: "Message Queues",
    url: "https://lnkd.in/g-jnNGDC",
    category: "Communication",
    difficulty: "Intermediate" as const,
  },
  {
    id: 25,
    title: "Bloom Filters",
    url: "https://lnkd.in/gfGjCrSZ",
    category: "Data Structures",
    difficulty: "Advanced" as const,
  },
  {
    id: 26,
    title: "Idempotency",
    url: "https://lnkd.in/gDB3AJij",
    category: "Theory",
    difficulty: "Intermediate" as const,
  },
  {
    id: 27,
    title: "Concurrency vs Parallelism",
    url: "https://lnkd.in/gGZXhjBD",
    category: "Theory",
    difficulty: "Intermediate" as const,
  },
  {
    id: 28,
    title: "Stateful vs Stateless Architecture",
    url: "https://lnkd.in/gz_ccK-Y",
    category: "Architecture",
    difficulty: "Intermediate" as const,
  },
  {
    id: 29,
    title: "Long Polling vs WebSockets",
    url: "https://lnkd.in/d9xKD28K",
    category: "Communication",
    difficulty: "Intermediate" as const,
  },
  {
    id: 30,
    title: "Batch vs Stream Processing",
    url: "https://lnkd.in/gKtj_qWh",
    category: "Processing",
    difficulty: "Advanced" as const,
  },
]
