export const roadmapData = [
  {
    id: 1,
    title: "APIs",
    url: "https://blog.algomaster.io/p/whats-an-api",
    category: "Communication",
    difficulty: "Beginner" as const,
  },
  {
    id: 2,
    title: "Webhooks",
    url: "https://blog.algomaster.io/p/what-are-webhooks",
    category: "Communication",
    difficulty: "Beginner" as const,
  },
  {
    id: 3,
    title: "REST vs GraphQL",
    url: "https://blog.algomaster.io/p/rest-vs-graphql",
    category: "Communication",
    difficulty: "Intermediate" as const,
  },
  {
    id: 4,
    title: "API Gateway",
    url: "https://blog.algomaster.io/p/what-is-an-api-gateway",
    category: "Infrastructure",
    difficulty: "Intermediate" as const,
  },
  {
    id: 5,
    title: "Load Balancers",
    url: "https://blog.algomaster.io/p/load-balancer-vs-reverse-proxy-vs-api-gateway",
    category: "Infrastructure",
    difficulty: "Intermediate" as const,
  },
  {
    id: 6,
    title: "Load Balancing Algorithms",
    url: "https://blog.algomaster.io/p/load-balancing-algorithms-explained-with-code",
    category: "Infrastructure",
    difficulty: "Advanced" as const,
  },
  {
    id: 7,
    title: "Proxy vs Reverse Proxy",
    url: "https://blog.algomaster.io/p/proxy-vs-reverse-proxy-explained",
    category: "Infrastructure",
    difficulty: "Intermediate" as const,
  },
  {
    id: 8,
    title: "Scalability",
    url: "https://blog.algomaster.io/p/scalability",
    category: "Architecture",
    difficulty: "Intermediate" as const,
  },
  {
    id: 9,
    title: "Availability",
    url: "https://blog.algomaster.io/p/system-design-what-is-availability",
    category: "Architecture",
    difficulty: "Intermediate" as const,
  },
  {
    id: 10,
    title: "SPOF (Single Point of Failure)",
    url: "https://blog.algomaster.io/p/system-design-how-to-avoid-single-point-of-failures",
    category: "Architecture",
    difficulty: "Intermediate" as const,
  },
  {
    id: 11,
    title: "CAP Theorem",
    url: "https://blog.algomaster.io/p/cap-theorem-explained",
    category: "Theory",
    difficulty: "Advanced" as const,
  },
  {
    id: 12,
    title: "Database Types",
    url: "https://blog.algomaster.io/p/15-types-of-databases",
    category: "Database",
    difficulty: "Beginner" as const,
  },
  {
    id: 13,
    title: "SQL vs NoSQL",
    url: "https://blog.algomaster.io/p/sql-vs-nosql-7-key-differences",
    category: "Database",
    difficulty: "Intermediate" as const,
  },
  {
    id: 14,
    title: "ACID Transactions",
    url: "https://blog.algomaster.io/p/what-are-acid-transactions-in-databases",
    category: "Database",
    difficulty: "Intermediate" as const,
  },
  {
    id: 15,
    title: "Database Indexes",
    url: "https://blog.algomaster.io/p/a-detailed-guide-on-database-indexes",
    category: "Database",
    difficulty: "Intermediate" as const,
  },
  {
    id: 16,
    title: "Sharding vs Partitioning",
    url: "https://blog.algomaster.io/p/sharding-vs-partitioning",
    category: "Database",
    difficulty: "Advanced" as const,
  },
  {
    id: 17,
    title: "Consistent Hashing",
    url: "https://blog.algomaster.io/p/consistent-hashing-explained",
    category: "Database",
    difficulty: "Advanced" as const,
  },
  {
    id: 18,
    title: "CDC (Change Data Capture)",
    url: "https://blog.algomaster.io/p/change-data-capture-cdc",
    category: "Database",
    difficulty: "Advanced" as const,
  },
  {
    id: 19,
    title: "Caching",
    url: "https://blog.algomaster.io/p/4d7d6f8a-6803-4c7b-85ca-864c87c2cbf2",
    category: "Performance",
    difficulty: "Beginner" as const,
  },
  {
    id: 20,
    title: "Caching Strategies",
    url: "https://blog.algomaster.io/p/top-5-caching-strategies-explained",
    category: "Performance",
    difficulty: "Intermediate" as const,
  },
  {
    id: 21,
    title: "Cache Eviction Policies",
    url: "https://blog.algomaster.io/p/7-cache-eviction-strategies",
    category: "Performance",
    difficulty: "Intermediate" as const,
  },
  {
    id: 22,
    title: "CDN (Content Delivery Network)",
    url: "https://blog.algomaster.io/p/content-delivery-networks",
    category: "Performance",
    difficulty: "Intermediate" as const,
  },
  {
    id: 23,
    title: "Rate Limiting Algorithms",
    url: "https://blog.algomaster.io/p/rate-limiting-algorithms-explained-with-code",
    category: "Security",
    difficulty: "Intermediate" as const,
  },
  {
    id: 24,
    title: "Message Queues",
    url: "https://blog.algomaster.io/p/message-queues",
    category: "Communication",
    difficulty: "Intermediate" as const,
  },
  {
    id: 25,
    title: "Bloom Filters",
    url: "https://blog.algomaster.io/p/bloom-filters",
    category: "Data Structures",
    difficulty: "Advanced" as const,
  },
  {
    id: 26,
    title: "Idempotency",
    url: "https://blog.algomaster.io/p/idempotency-in-distributed-systems",
    category: "Theory",
    difficulty: "Intermediate" as const,
  },
  {
    id: 27,
    title: "Concurrency vs Parallelism",
    url: "https://blog.algomaster.io/p/concurrency-vs-parallelism",
    category: "Theory",
    difficulty: "Intermediate" as const,
  },
  {
    id: 28,
    title: "Stateful vs Stateless Architecture",
    url: "https://blog.algomaster.io/p/stateful-vs-stateless-architecture",
    category: "Architecture",
    difficulty: "Intermediate" as const,
  },
  {
    id: 29,
    title: "Long Polling vs WebSockets",
    url: "https://blog.algomaster.io/p/long-polling-vs-websockets",
    category: "Communication",
    difficulty: "Intermediate" as const,
  },
  {
    id: 30,
    title: "Batch vs Stream Processing",
    url: "https://blog.algomaster.io/p/batch-processing-vs-stream-processing",
    category: "Processing",
    difficulty: "Advanced" as const,
  },
]
