// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cnjsqpirfdqgzxakllcq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNuanNxcGlyZmRxZ3p4YWtsbGNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0Njc1OTcsImV4cCI6MjA3MDA0MzU5N30.A_HrQybpPNzHU3aw2t1b6cp_80ULkCEYf9ZCexxaKn4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});